# Generated by Django 3.0.7 on 2020-06-11 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200611_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='answerA',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='question',
            name='answerB',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='question',
            name='answerC',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='question',
            name='answerD',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='question',
            name='corrAns',
            field=models.CharField(default='', max_length=1),
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
    ]
